version: '3.8'

services:
  minio1:
    image: minio/minio
    container_name: minio1
    restart: always
    volumes:
      - .docker/minio/data1:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server http://minio{1...2}/data  --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  minio2:
    image: minio/minio
    container_name: minio2
    restart: always
    volumes:
      - .docker/minio/data2:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server http://minio{1...2}/data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio-nginx:
    image: nginx
    container_name: minio-nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9000:9000 # Minio S3 API
      - 9001:9001 # Minio console
    depends_on:
      - minio1
      - minio2